#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
# SPDX-FileCopyrightText: Netresearch DTT GmbH

## Description: Set up all nr-browser-ai TYPO3 environments
## Usage: setup
## Example: ddev setup

set -euo pipefail

/mnt/ddev_config/commands/web/install-all
